# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    
env:
  AZURE_WEBAPP_NAME: cttodoappdemo4   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: .      # set this to the path to your web app project, defaults to the repository root
  #NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        cache-dependency-path: ./todo/package-lock.json
    - run: npm install
      working-directory: ./todo
    - run: npm run build --if-present
      working-directory: ./todo


    - name: Upload to Artifactory
      uses: actions/upload-artifact@v2.3.1
      with:
        name: todo-app
        path: ./todo/dist/todo
        if-no-files-found: error
    
      
  deploy:
  
    runs-on: ubuntu-latest
    
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.0
      with:
        # Artifact name
        name: todo-app
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp 
      uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} 
